# .streamlit/secrets.toml

# ===================================================
# Credenciais do Google Cloud para a Planilha
# ===================================================
[gcp_service_account]
type = "service_account"
project_id = "streamlit-he"
private_key_id = "f50bb2b721c8cd5bf38f4e83441a9d973d2f5b12"
private_key = """-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCc88AZmhhsj/o6\nag79OT66DlRRFuMO+9xf/yTeQpix4x7j5PxaKyfbrLthB8R1cI6DWRJO2GB0Mg84\nYjA1HOU1v5kKt0oDNVPE6+u1pOShyBDNl+9HLNWqRy2t9pt1er97Rq/72MnERP8k\nP/XI/IHAiIkXq1VynSuUiLmwGGmA5A2ccn7Uxu8E7Giv8zm+k5Iguik48e1cO2MZ\ncqt2FVYyZJo0QgmJeheB0Acc17iqv1Aavh8rSmYBuDkJ1xKGEJ/681XI9Nw0Mq8K\nUB7CENFepHhCmyvwAy3Z/a/LQfwwLgvjDy/F/mvgEcNQjqXcXlfYfxfyNNjlEnzB\nB/9lirDfAgMBAAECggEAQCDiETPindz4H0z9Yd61b/zx244P6SvkX77WuA+a5zgH\nA5OovkjayMmbaCptzZRXTnii399ODbv0dxO7YcA0MRFffT7luUjdON0yWm4M0sN1\nhiN5q2m4xZG+qtFTtJ0aRsrblfn+eri8TPnrOZtegqXm6epiB+oLB+4TfM2EshoY\nArQYLjCHZkelFqaK+cxoCU81Us+XqXwUNiKyG5TmMNFU7nYkAY6Zso/LF8csgSQA\nPbOq2YHo9rr8+HyK++6M1PIssBotZHkxgcMyqCPdB4WQV3w81+FRDc1RGR+6PJbY\nQ9o7veTOE4C1iXB6PEZE7kh0M0kE30cF/wttSnPxWQKBgQDWHCp1blJvFgfRoNcj\nk1lX7Uy72paRwRLbVn3pmB++m8tC2RwE68u76xZx7r0pcxToLc21F4fTJkFWx4gn\nUntIQytoRKaQ+0frRPlbioBLBUXOP/eAs3bNFI365OurEoan6CHrcLe1roRrccbb\n+C0Wa1xUjP2mO+nbDKQG2+w9WQKBgQC7qMv6ou5qigRyNf/m15/CSgj+0ED+49Bk\ncaHwbXpczNWLbFjDpHo36vmQNn2GTKtkTN4hPtOZy/QMt2XCLbtu2VeblSvi8TqE\nQy76cYc7CNBonhzFOZe7QNPAQM2HqK2v99MUmPUptRHpCClx8HaEifOX07OVwnhz\n1XcJHIeA9wKBgDabqmyW/aldehMKLbTiIPhfCqIi5yI3lyKgFa8dYINR4u6ixxWu\nOiEsnWXjmRVYR63L+NpGLRs6d5G1hFFbJRxSHWETmVQC8t3bkqm5Um1P4/Tttad6\nnkNCCdBC0KSqLfPnLbeJ4SESaK2qsChsTLuaGEtsRkk+oK+AstkZAFDJAoGAP3S/\nrPwFZM9Q25H4+4U0R42jZw7iu44rfJuUJ+nNM64sE55KkbV/goMZarOSVKR+XEdF\n4bYN9XarCtXFOhkexUgHQNv7YB00LV9Odm+HS+YaGxZEIkjsTuyH7f27wkC+or9J\niDCEzlqlOMiCwz2Nxhmj3lY+5shA1OJ9Av67r1cCgYAmsDhL89smkOqBv3/TmJhX\n0frueru+xU5kTZmP/oj2vPrXo2tQGbB8UPIbPzgJHq38t8rAmJ0zd6W8rpfEeaGM\nv0YqmFxzjSzUe8wJ1LyI9ZlFDQVq9EcBQYv0DSl4CYjVUtDA2MQgHkwI/zCkM7Lp\nbdztsoL9pevgNLrPrpjbXA==\n-----END PRIVATE KEY-----"""
client_email = "leitor-planilhas@streamlit-he.iam.gserviceaccount.com"
client_id = "105573683640169531346"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/leitor-planilhas%40streamlit-he.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


# ===================================================
# Credenciais do Supabase
# ===================================================
[supabase]
connection_string = "postgresql://postgres.kwbuzstpzbipoijfsvqn:JFS92837465@aws-0-sa-east-1.pooler.supabase.com:5432/postgres"


